spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
      apache:
        tomcat:
          websocket: DEBUG